### ISSUE TITLE
Smart contract

### ISSUE THREAD

**Issue by cromatikap** [cromatikap/pocketsub#14]
Features to add:
- [x] `function getShopSubscriptions(address owner)` | Dependency of #10 
- [x] add NFT metadata in resource settings | Dependency of #17 
- [x] get NFT metadata + mint price | Dependency of #13
